// Code generated by ent, DO NOT EDIT.

package payloadauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the payloadauditlog type in the database.
	Label = "payload_audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAPIKeyName holds the string denoting the api_key_name field in the database.
	FieldAPIKeyName = "api_key_name"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldInputExcerpt holds the string denoting the input_excerpt field in the database.
	FieldInputExcerpt = "input_excerpt"
	// FieldOutputExcerpt holds the string denoting the output_excerpt field in the database.
	FieldOutputExcerpt = "output_excerpt"
	// FieldInputBody holds the string denoting the input_body field in the database.
	FieldInputBody = "input_body"
	// FieldOutputBody holds the string denoting the output_body field in the database.
	FieldOutputBody = "output_body"
	// FieldInputFormat holds the string denoting the input_format field in the database.
	FieldInputFormat = "input_format"
	// FieldOutputFormat holds the string denoting the output_format field in the database.
	FieldOutputFormat = "output_format"
	// FieldInputBytes holds the string denoting the input_bytes field in the database.
	FieldInputBytes = "input_bytes"
	// FieldOutputBytes holds the string denoting the output_bytes field in the database.
	FieldOutputBytes = "output_bytes"
	// FieldInputTruncated holds the string denoting the input_truncated field in the database.
	FieldInputTruncated = "input_truncated"
	// FieldOutputTruncated holds the string denoting the output_truncated field in the database.
	FieldOutputTruncated = "output_truncated"
	// FieldOutputOmitted holds the string denoting the output_omitted field in the database.
	FieldOutputOmitted = "output_omitted"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// Table holds the table name of the payloadauditlog in the database.
	Table = "payload_audit_logs"
)

// Columns holds all SQL columns for payloadauditlog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRequestID,
	FieldUserID,
	FieldUserEmail,
	FieldAPIKeyID,
	FieldAPIKeyName,
	FieldGroupID,
	FieldGroupName,
	FieldClientIP,
	FieldEndpoint,
	FieldProvider,
	FieldModel,
	FieldUpstreamModel,
	FieldStream,
	FieldStatusCode,
	FieldDurationMs,
	FieldInputExcerpt,
	FieldOutputExcerpt,
	FieldInputBody,
	FieldOutputBody,
	FieldInputFormat,
	FieldOutputFormat,
	FieldInputBytes,
	FieldOutputBytes,
	FieldInputTruncated,
	FieldOutputTruncated,
	FieldOutputOmitted,
	FieldErrorMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultUserEmail holds the default value on creation for the "user_email" field.
	DefaultUserEmail string
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// DefaultAPIKeyName holds the default value on creation for the "api_key_name" field.
	DefaultAPIKeyName string
	// APIKeyNameValidator is a validator for the "api_key_name" field. It is called by the builders before save.
	APIKeyNameValidator func(string) error
	// DefaultGroupName holds the default value on creation for the "group_name" field.
	DefaultGroupName string
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// DefaultClientIP holds the default value on creation for the "client_ip" field.
	DefaultClientIP string
	// ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	ClientIPValidator func(string) error
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultUpstreamModel holds the default value on creation for the "upstream_model" field.
	DefaultUpstreamModel string
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultStatusCode holds the default value on creation for the "status_code" field.
	DefaultStatusCode int
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int
	// DefaultInputExcerpt holds the default value on creation for the "input_excerpt" field.
	DefaultInputExcerpt string
	// InputExcerptValidator is a validator for the "input_excerpt" field. It is called by the builders before save.
	InputExcerptValidator func(string) error
	// DefaultOutputExcerpt holds the default value on creation for the "output_excerpt" field.
	DefaultOutputExcerpt string
	// OutputExcerptValidator is a validator for the "output_excerpt" field. It is called by the builders before save.
	OutputExcerptValidator func(string) error
	// DefaultInputBody holds the default value on creation for the "input_body" field.
	DefaultInputBody string
	// DefaultOutputBody holds the default value on creation for the "output_body" field.
	DefaultOutputBody string
	// DefaultInputFormat holds the default value on creation for the "input_format" field.
	DefaultInputFormat string
	// InputFormatValidator is a validator for the "input_format" field. It is called by the builders before save.
	InputFormatValidator func(string) error
	// DefaultOutputFormat holds the default value on creation for the "output_format" field.
	DefaultOutputFormat string
	// OutputFormatValidator is a validator for the "output_format" field. It is called by the builders before save.
	OutputFormatValidator func(string) error
	// DefaultInputBytes holds the default value on creation for the "input_bytes" field.
	DefaultInputBytes int
	// DefaultOutputBytes holds the default value on creation for the "output_bytes" field.
	DefaultOutputBytes int
	// DefaultInputTruncated holds the default value on creation for the "input_truncated" field.
	DefaultInputTruncated bool
	// DefaultOutputTruncated holds the default value on creation for the "output_truncated" field.
	DefaultOutputTruncated bool
	// DefaultOutputOmitted holds the default value on creation for the "output_omitted" field.
	DefaultOutputOmitted bool
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
)

// OrderOption defines the ordering options for the PayloadAuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAPIKeyName orders the results by the api_key_name field.
func ByAPIKeyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyName, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByClientIP orders the results by the client_ip field.
func ByClientIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientIP, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByInputExcerpt orders the results by the input_excerpt field.
func ByInputExcerpt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputExcerpt, opts...).ToFunc()
}

// ByOutputExcerpt orders the results by the output_excerpt field.
func ByOutputExcerpt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputExcerpt, opts...).ToFunc()
}

// ByInputBody orders the results by the input_body field.
func ByInputBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputBody, opts...).ToFunc()
}

// ByOutputBody orders the results by the output_body field.
func ByOutputBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputBody, opts...).ToFunc()
}

// ByInputFormat orders the results by the input_format field.
func ByInputFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputFormat, opts...).ToFunc()
}

// ByOutputFormat orders the results by the output_format field.
func ByOutputFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputFormat, opts...).ToFunc()
}

// ByInputBytes orders the results by the input_bytes field.
func ByInputBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputBytes, opts...).ToFunc()
}

// ByOutputBytes orders the results by the output_bytes field.
func ByOutputBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputBytes, opts...).ToFunc()
}

// ByInputTruncated orders the results by the input_truncated field.
func ByInputTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTruncated, opts...).ToFunc()
}

// ByOutputTruncated orders the results by the output_truncated field.
func ByOutputTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTruncated, opts...).ToFunc()
}

// ByOutputOmitted orders the results by the output_omitted field.
func ByOutputOmitted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputOmitted, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}
