// Code generated by ent, DO NOT EDIT.

package payloadauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Woo0ood/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldRequestID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldUserID, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldUserEmail, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyName applies equality check predicate on the "api_key_name" field. It's identical to APIKeyNameEQ.
func APIKeyName(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldAPIKeyName, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldGroupID, v))
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldGroupName, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldClientIP, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldEndpoint, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldProvider, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldUpstreamModel, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldStream, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldDurationMs, v))
}

// InputExcerpt applies equality check predicate on the "input_excerpt" field. It's identical to InputExcerptEQ.
func InputExcerpt(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputExcerpt, v))
}

// OutputExcerpt applies equality check predicate on the "output_excerpt" field. It's identical to OutputExcerptEQ.
func OutputExcerpt(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputExcerpt, v))
}

// InputBody applies equality check predicate on the "input_body" field. It's identical to InputBodyEQ.
func InputBody(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputBody, v))
}

// OutputBody applies equality check predicate on the "output_body" field. It's identical to OutputBodyEQ.
func OutputBody(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputBody, v))
}

// InputFormat applies equality check predicate on the "input_format" field. It's identical to InputFormatEQ.
func InputFormat(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputFormat, v))
}

// OutputFormat applies equality check predicate on the "output_format" field. It's identical to OutputFormatEQ.
func OutputFormat(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputFormat, v))
}

// InputBytes applies equality check predicate on the "input_bytes" field. It's identical to InputBytesEQ.
func InputBytes(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputBytes, v))
}

// OutputBytes applies equality check predicate on the "output_bytes" field. It's identical to OutputBytesEQ.
func OutputBytes(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputBytes, v))
}

// InputTruncated applies equality check predicate on the "input_truncated" field. It's identical to InputTruncatedEQ.
func InputTruncated(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputTruncated, v))
}

// OutputTruncated applies equality check predicate on the "output_truncated" field. It's identical to OutputTruncatedEQ.
func OutputTruncated(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputTruncated, v))
}

// OutputOmitted applies equality check predicate on the "output_omitted" field. It's identical to OutputOmittedEQ.
func OutputOmitted(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputOmitted, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotNull(FieldUserID))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldUserEmail, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotNull(FieldAPIKeyID))
}

// APIKeyNameEQ applies the EQ predicate on the "api_key_name" field.
func APIKeyNameEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldAPIKeyName, v))
}

// APIKeyNameNEQ applies the NEQ predicate on the "api_key_name" field.
func APIKeyNameNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldAPIKeyName, v))
}

// APIKeyNameIn applies the In predicate on the "api_key_name" field.
func APIKeyNameIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldAPIKeyName, vs...))
}

// APIKeyNameNotIn applies the NotIn predicate on the "api_key_name" field.
func APIKeyNameNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldAPIKeyName, vs...))
}

// APIKeyNameGT applies the GT predicate on the "api_key_name" field.
func APIKeyNameGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldAPIKeyName, v))
}

// APIKeyNameGTE applies the GTE predicate on the "api_key_name" field.
func APIKeyNameGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldAPIKeyName, v))
}

// APIKeyNameLT applies the LT predicate on the "api_key_name" field.
func APIKeyNameLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldAPIKeyName, v))
}

// APIKeyNameLTE applies the LTE predicate on the "api_key_name" field.
func APIKeyNameLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldAPIKeyName, v))
}

// APIKeyNameContains applies the Contains predicate on the "api_key_name" field.
func APIKeyNameContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldAPIKeyName, v))
}

// APIKeyNameHasPrefix applies the HasPrefix predicate on the "api_key_name" field.
func APIKeyNameHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldAPIKeyName, v))
}

// APIKeyNameHasSuffix applies the HasSuffix predicate on the "api_key_name" field.
func APIKeyNameHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldAPIKeyName, v))
}

// APIKeyNameEqualFold applies the EqualFold predicate on the "api_key_name" field.
func APIKeyNameEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldAPIKeyName, v))
}

// APIKeyNameContainsFold applies the ContainsFold predicate on the "api_key_name" field.
func APIKeyNameContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldAPIKeyName, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotNull(FieldGroupID))
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldGroupName, v))
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldGroupName, v))
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldGroupName, vs...))
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldGroupName, vs...))
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldGroupName, v))
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldGroupName, v))
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldGroupName, v))
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldGroupName, v))
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldGroupName, v))
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldGroupName, v))
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldGroupName, v))
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldGroupName, v))
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldGroupName, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldClientIP, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldEndpoint, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldProvider, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldStream, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldStatusCode, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldDurationMs, v))
}

// InputExcerptEQ applies the EQ predicate on the "input_excerpt" field.
func InputExcerptEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputExcerpt, v))
}

// InputExcerptNEQ applies the NEQ predicate on the "input_excerpt" field.
func InputExcerptNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldInputExcerpt, v))
}

// InputExcerptIn applies the In predicate on the "input_excerpt" field.
func InputExcerptIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldInputExcerpt, vs...))
}

// InputExcerptNotIn applies the NotIn predicate on the "input_excerpt" field.
func InputExcerptNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldInputExcerpt, vs...))
}

// InputExcerptGT applies the GT predicate on the "input_excerpt" field.
func InputExcerptGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldInputExcerpt, v))
}

// InputExcerptGTE applies the GTE predicate on the "input_excerpt" field.
func InputExcerptGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldInputExcerpt, v))
}

// InputExcerptLT applies the LT predicate on the "input_excerpt" field.
func InputExcerptLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldInputExcerpt, v))
}

// InputExcerptLTE applies the LTE predicate on the "input_excerpt" field.
func InputExcerptLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldInputExcerpt, v))
}

// InputExcerptContains applies the Contains predicate on the "input_excerpt" field.
func InputExcerptContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldInputExcerpt, v))
}

// InputExcerptHasPrefix applies the HasPrefix predicate on the "input_excerpt" field.
func InputExcerptHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldInputExcerpt, v))
}

// InputExcerptHasSuffix applies the HasSuffix predicate on the "input_excerpt" field.
func InputExcerptHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldInputExcerpt, v))
}

// InputExcerptEqualFold applies the EqualFold predicate on the "input_excerpt" field.
func InputExcerptEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldInputExcerpt, v))
}

// InputExcerptContainsFold applies the ContainsFold predicate on the "input_excerpt" field.
func InputExcerptContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldInputExcerpt, v))
}

// OutputExcerptEQ applies the EQ predicate on the "output_excerpt" field.
func OutputExcerptEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputExcerpt, v))
}

// OutputExcerptNEQ applies the NEQ predicate on the "output_excerpt" field.
func OutputExcerptNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldOutputExcerpt, v))
}

// OutputExcerptIn applies the In predicate on the "output_excerpt" field.
func OutputExcerptIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldOutputExcerpt, vs...))
}

// OutputExcerptNotIn applies the NotIn predicate on the "output_excerpt" field.
func OutputExcerptNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldOutputExcerpt, vs...))
}

// OutputExcerptGT applies the GT predicate on the "output_excerpt" field.
func OutputExcerptGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldOutputExcerpt, v))
}

// OutputExcerptGTE applies the GTE predicate on the "output_excerpt" field.
func OutputExcerptGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldOutputExcerpt, v))
}

// OutputExcerptLT applies the LT predicate on the "output_excerpt" field.
func OutputExcerptLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldOutputExcerpt, v))
}

// OutputExcerptLTE applies the LTE predicate on the "output_excerpt" field.
func OutputExcerptLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldOutputExcerpt, v))
}

// OutputExcerptContains applies the Contains predicate on the "output_excerpt" field.
func OutputExcerptContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldOutputExcerpt, v))
}

// OutputExcerptHasPrefix applies the HasPrefix predicate on the "output_excerpt" field.
func OutputExcerptHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldOutputExcerpt, v))
}

// OutputExcerptHasSuffix applies the HasSuffix predicate on the "output_excerpt" field.
func OutputExcerptHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldOutputExcerpt, v))
}

// OutputExcerptEqualFold applies the EqualFold predicate on the "output_excerpt" field.
func OutputExcerptEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldOutputExcerpt, v))
}

// OutputExcerptContainsFold applies the ContainsFold predicate on the "output_excerpt" field.
func OutputExcerptContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldOutputExcerpt, v))
}

// InputBodyEQ applies the EQ predicate on the "input_body" field.
func InputBodyEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputBody, v))
}

// InputBodyNEQ applies the NEQ predicate on the "input_body" field.
func InputBodyNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldInputBody, v))
}

// InputBodyIn applies the In predicate on the "input_body" field.
func InputBodyIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldInputBody, vs...))
}

// InputBodyNotIn applies the NotIn predicate on the "input_body" field.
func InputBodyNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldInputBody, vs...))
}

// InputBodyGT applies the GT predicate on the "input_body" field.
func InputBodyGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldInputBody, v))
}

// InputBodyGTE applies the GTE predicate on the "input_body" field.
func InputBodyGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldInputBody, v))
}

// InputBodyLT applies the LT predicate on the "input_body" field.
func InputBodyLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldInputBody, v))
}

// InputBodyLTE applies the LTE predicate on the "input_body" field.
func InputBodyLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldInputBody, v))
}

// InputBodyContains applies the Contains predicate on the "input_body" field.
func InputBodyContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldInputBody, v))
}

// InputBodyHasPrefix applies the HasPrefix predicate on the "input_body" field.
func InputBodyHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldInputBody, v))
}

// InputBodyHasSuffix applies the HasSuffix predicate on the "input_body" field.
func InputBodyHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldInputBody, v))
}

// InputBodyEqualFold applies the EqualFold predicate on the "input_body" field.
func InputBodyEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldInputBody, v))
}

// InputBodyContainsFold applies the ContainsFold predicate on the "input_body" field.
func InputBodyContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldInputBody, v))
}

// OutputBodyEQ applies the EQ predicate on the "output_body" field.
func OutputBodyEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputBody, v))
}

// OutputBodyNEQ applies the NEQ predicate on the "output_body" field.
func OutputBodyNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldOutputBody, v))
}

// OutputBodyIn applies the In predicate on the "output_body" field.
func OutputBodyIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldOutputBody, vs...))
}

// OutputBodyNotIn applies the NotIn predicate on the "output_body" field.
func OutputBodyNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldOutputBody, vs...))
}

// OutputBodyGT applies the GT predicate on the "output_body" field.
func OutputBodyGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldOutputBody, v))
}

// OutputBodyGTE applies the GTE predicate on the "output_body" field.
func OutputBodyGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldOutputBody, v))
}

// OutputBodyLT applies the LT predicate on the "output_body" field.
func OutputBodyLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldOutputBody, v))
}

// OutputBodyLTE applies the LTE predicate on the "output_body" field.
func OutputBodyLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldOutputBody, v))
}

// OutputBodyContains applies the Contains predicate on the "output_body" field.
func OutputBodyContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldOutputBody, v))
}

// OutputBodyHasPrefix applies the HasPrefix predicate on the "output_body" field.
func OutputBodyHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldOutputBody, v))
}

// OutputBodyHasSuffix applies the HasSuffix predicate on the "output_body" field.
func OutputBodyHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldOutputBody, v))
}

// OutputBodyEqualFold applies the EqualFold predicate on the "output_body" field.
func OutputBodyEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldOutputBody, v))
}

// OutputBodyContainsFold applies the ContainsFold predicate on the "output_body" field.
func OutputBodyContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldOutputBody, v))
}

// InputFormatEQ applies the EQ predicate on the "input_format" field.
func InputFormatEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputFormat, v))
}

// InputFormatNEQ applies the NEQ predicate on the "input_format" field.
func InputFormatNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldInputFormat, v))
}

// InputFormatIn applies the In predicate on the "input_format" field.
func InputFormatIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldInputFormat, vs...))
}

// InputFormatNotIn applies the NotIn predicate on the "input_format" field.
func InputFormatNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldInputFormat, vs...))
}

// InputFormatGT applies the GT predicate on the "input_format" field.
func InputFormatGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldInputFormat, v))
}

// InputFormatGTE applies the GTE predicate on the "input_format" field.
func InputFormatGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldInputFormat, v))
}

// InputFormatLT applies the LT predicate on the "input_format" field.
func InputFormatLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldInputFormat, v))
}

// InputFormatLTE applies the LTE predicate on the "input_format" field.
func InputFormatLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldInputFormat, v))
}

// InputFormatContains applies the Contains predicate on the "input_format" field.
func InputFormatContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldInputFormat, v))
}

// InputFormatHasPrefix applies the HasPrefix predicate on the "input_format" field.
func InputFormatHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldInputFormat, v))
}

// InputFormatHasSuffix applies the HasSuffix predicate on the "input_format" field.
func InputFormatHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldInputFormat, v))
}

// InputFormatEqualFold applies the EqualFold predicate on the "input_format" field.
func InputFormatEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldInputFormat, v))
}

// InputFormatContainsFold applies the ContainsFold predicate on the "input_format" field.
func InputFormatContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldInputFormat, v))
}

// OutputFormatEQ applies the EQ predicate on the "output_format" field.
func OutputFormatEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputFormat, v))
}

// OutputFormatNEQ applies the NEQ predicate on the "output_format" field.
func OutputFormatNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldOutputFormat, v))
}

// OutputFormatIn applies the In predicate on the "output_format" field.
func OutputFormatIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldOutputFormat, vs...))
}

// OutputFormatNotIn applies the NotIn predicate on the "output_format" field.
func OutputFormatNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldOutputFormat, vs...))
}

// OutputFormatGT applies the GT predicate on the "output_format" field.
func OutputFormatGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldOutputFormat, v))
}

// OutputFormatGTE applies the GTE predicate on the "output_format" field.
func OutputFormatGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldOutputFormat, v))
}

// OutputFormatLT applies the LT predicate on the "output_format" field.
func OutputFormatLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldOutputFormat, v))
}

// OutputFormatLTE applies the LTE predicate on the "output_format" field.
func OutputFormatLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldOutputFormat, v))
}

// OutputFormatContains applies the Contains predicate on the "output_format" field.
func OutputFormatContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldOutputFormat, v))
}

// OutputFormatHasPrefix applies the HasPrefix predicate on the "output_format" field.
func OutputFormatHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldOutputFormat, v))
}

// OutputFormatHasSuffix applies the HasSuffix predicate on the "output_format" field.
func OutputFormatHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldOutputFormat, v))
}

// OutputFormatEqualFold applies the EqualFold predicate on the "output_format" field.
func OutputFormatEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldOutputFormat, v))
}

// OutputFormatContainsFold applies the ContainsFold predicate on the "output_format" field.
func OutputFormatContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldOutputFormat, v))
}

// InputBytesEQ applies the EQ predicate on the "input_bytes" field.
func InputBytesEQ(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputBytes, v))
}

// InputBytesNEQ applies the NEQ predicate on the "input_bytes" field.
func InputBytesNEQ(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldInputBytes, v))
}

// InputBytesIn applies the In predicate on the "input_bytes" field.
func InputBytesIn(vs ...int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldInputBytes, vs...))
}

// InputBytesNotIn applies the NotIn predicate on the "input_bytes" field.
func InputBytesNotIn(vs ...int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldInputBytes, vs...))
}

// InputBytesGT applies the GT predicate on the "input_bytes" field.
func InputBytesGT(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldInputBytes, v))
}

// InputBytesGTE applies the GTE predicate on the "input_bytes" field.
func InputBytesGTE(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldInputBytes, v))
}

// InputBytesLT applies the LT predicate on the "input_bytes" field.
func InputBytesLT(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldInputBytes, v))
}

// InputBytesLTE applies the LTE predicate on the "input_bytes" field.
func InputBytesLTE(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldInputBytes, v))
}

// OutputBytesEQ applies the EQ predicate on the "output_bytes" field.
func OutputBytesEQ(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputBytes, v))
}

// OutputBytesNEQ applies the NEQ predicate on the "output_bytes" field.
func OutputBytesNEQ(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldOutputBytes, v))
}

// OutputBytesIn applies the In predicate on the "output_bytes" field.
func OutputBytesIn(vs ...int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldOutputBytes, vs...))
}

// OutputBytesNotIn applies the NotIn predicate on the "output_bytes" field.
func OutputBytesNotIn(vs ...int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldOutputBytes, vs...))
}

// OutputBytesGT applies the GT predicate on the "output_bytes" field.
func OutputBytesGT(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldOutputBytes, v))
}

// OutputBytesGTE applies the GTE predicate on the "output_bytes" field.
func OutputBytesGTE(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldOutputBytes, v))
}

// OutputBytesLT applies the LT predicate on the "output_bytes" field.
func OutputBytesLT(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldOutputBytes, v))
}

// OutputBytesLTE applies the LTE predicate on the "output_bytes" field.
func OutputBytesLTE(v int) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldOutputBytes, v))
}

// InputTruncatedEQ applies the EQ predicate on the "input_truncated" field.
func InputTruncatedEQ(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldInputTruncated, v))
}

// InputTruncatedNEQ applies the NEQ predicate on the "input_truncated" field.
func InputTruncatedNEQ(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldInputTruncated, v))
}

// OutputTruncatedEQ applies the EQ predicate on the "output_truncated" field.
func OutputTruncatedEQ(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputTruncated, v))
}

// OutputTruncatedNEQ applies the NEQ predicate on the "output_truncated" field.
func OutputTruncatedNEQ(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldOutputTruncated, v))
}

// OutputOmittedEQ applies the EQ predicate on the "output_omitted" field.
func OutputOmittedEQ(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldOutputOmitted, v))
}

// OutputOmittedNEQ applies the NEQ predicate on the "output_omitted" field.
func OutputOmittedNEQ(v bool) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldOutputOmitted, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PayloadAuditLog) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PayloadAuditLog) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PayloadAuditLog) predicate.PayloadAuditLog {
	return predicate.PayloadAuditLog(sql.NotPredicates(p))
}
