// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Woo0ood/sub2api/ent/payloadauditlog"
	"github.com/Woo0ood/sub2api/ent/predicate"
)

// PayloadAuditLogUpdate is the builder for updating PayloadAuditLog entities.
type PayloadAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *PayloadAuditLogMutation
}

// Where appends a list predicates to the PayloadAuditLogUpdate builder.
func (_u *PayloadAuditLogUpdate) Where(ps ...predicate.PayloadAuditLog) *PayloadAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PayloadAuditLogUpdate) SetUpdatedAt(v time.Time) *PayloadAuditLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *PayloadAuditLogUpdate) SetRequestID(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableRequestID(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PayloadAuditLogUpdate) SetUserID(v int64) *PayloadAuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableUserID(v *int64) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *PayloadAuditLogUpdate) AddUserID(v int64) *PayloadAuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *PayloadAuditLogUpdate) ClearUserID() *PayloadAuditLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *PayloadAuditLogUpdate) SetUserEmail(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableUserEmail(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *PayloadAuditLogUpdate) SetAPIKeyID(v int64) *PayloadAuditLogUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableAPIKeyID(v *int64) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *PayloadAuditLogUpdate) AddAPIKeyID(v int64) *PayloadAuditLogUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *PayloadAuditLogUpdate) ClearAPIKeyID() *PayloadAuditLogUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAPIKeyName sets the "api_key_name" field.
func (_u *PayloadAuditLogUpdate) SetAPIKeyName(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetAPIKeyName(v)
	return _u
}

// SetNillableAPIKeyName sets the "api_key_name" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableAPIKeyName(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetAPIKeyName(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PayloadAuditLogUpdate) SetGroupID(v int64) *PayloadAuditLogUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableGroupID(v *int64) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *PayloadAuditLogUpdate) AddGroupID(v int64) *PayloadAuditLogUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *PayloadAuditLogUpdate) ClearGroupID() *PayloadAuditLogUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *PayloadAuditLogUpdate) SetGroupName(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableGroupName(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *PayloadAuditLogUpdate) SetClientIP(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableClientIP(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *PayloadAuditLogUpdate) SetEndpoint(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableEndpoint(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PayloadAuditLogUpdate) SetProvider(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableProvider(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *PayloadAuditLogUpdate) SetModel(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableModel(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *PayloadAuditLogUpdate) SetUpstreamModel(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableUpstreamModel(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetStream sets the "stream" field.
func (_u *PayloadAuditLogUpdate) SetStream(v bool) *PayloadAuditLogUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableStream(v *bool) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *PayloadAuditLogUpdate) SetStatusCode(v int) *PayloadAuditLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableStatusCode(v *int) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *PayloadAuditLogUpdate) AddStatusCode(v int) *PayloadAuditLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *PayloadAuditLogUpdate) SetDurationMs(v int) *PayloadAuditLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableDurationMs(v *int) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *PayloadAuditLogUpdate) AddDurationMs(v int) *PayloadAuditLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetInputExcerpt sets the "input_excerpt" field.
func (_u *PayloadAuditLogUpdate) SetInputExcerpt(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetInputExcerpt(v)
	return _u
}

// SetNillableInputExcerpt sets the "input_excerpt" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableInputExcerpt(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetInputExcerpt(*v)
	}
	return _u
}

// SetOutputExcerpt sets the "output_excerpt" field.
func (_u *PayloadAuditLogUpdate) SetOutputExcerpt(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetOutputExcerpt(v)
	return _u
}

// SetNillableOutputExcerpt sets the "output_excerpt" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableOutputExcerpt(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetOutputExcerpt(*v)
	}
	return _u
}

// SetInputBody sets the "input_body" field.
func (_u *PayloadAuditLogUpdate) SetInputBody(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetInputBody(v)
	return _u
}

// SetNillableInputBody sets the "input_body" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableInputBody(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetInputBody(*v)
	}
	return _u
}

// SetOutputBody sets the "output_body" field.
func (_u *PayloadAuditLogUpdate) SetOutputBody(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetOutputBody(v)
	return _u
}

// SetNillableOutputBody sets the "output_body" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableOutputBody(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetOutputBody(*v)
	}
	return _u
}

// SetInputFormat sets the "input_format" field.
func (_u *PayloadAuditLogUpdate) SetInputFormat(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetInputFormat(v)
	return _u
}

// SetNillableInputFormat sets the "input_format" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableInputFormat(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetInputFormat(*v)
	}
	return _u
}

// SetOutputFormat sets the "output_format" field.
func (_u *PayloadAuditLogUpdate) SetOutputFormat(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetOutputFormat(v)
	return _u
}

// SetNillableOutputFormat sets the "output_format" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableOutputFormat(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetOutputFormat(*v)
	}
	return _u
}

// SetInputBytes sets the "input_bytes" field.
func (_u *PayloadAuditLogUpdate) SetInputBytes(v int) *PayloadAuditLogUpdate {
	_u.mutation.ResetInputBytes()
	_u.mutation.SetInputBytes(v)
	return _u
}

// SetNillableInputBytes sets the "input_bytes" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableInputBytes(v *int) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetInputBytes(*v)
	}
	return _u
}

// AddInputBytes adds value to the "input_bytes" field.
func (_u *PayloadAuditLogUpdate) AddInputBytes(v int) *PayloadAuditLogUpdate {
	_u.mutation.AddInputBytes(v)
	return _u
}

// SetOutputBytes sets the "output_bytes" field.
func (_u *PayloadAuditLogUpdate) SetOutputBytes(v int) *PayloadAuditLogUpdate {
	_u.mutation.ResetOutputBytes()
	_u.mutation.SetOutputBytes(v)
	return _u
}

// SetNillableOutputBytes sets the "output_bytes" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableOutputBytes(v *int) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetOutputBytes(*v)
	}
	return _u
}

// AddOutputBytes adds value to the "output_bytes" field.
func (_u *PayloadAuditLogUpdate) AddOutputBytes(v int) *PayloadAuditLogUpdate {
	_u.mutation.AddOutputBytes(v)
	return _u
}

// SetInputTruncated sets the "input_truncated" field.
func (_u *PayloadAuditLogUpdate) SetInputTruncated(v bool) *PayloadAuditLogUpdate {
	_u.mutation.SetInputTruncated(v)
	return _u
}

// SetNillableInputTruncated sets the "input_truncated" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableInputTruncated(v *bool) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetInputTruncated(*v)
	}
	return _u
}

// SetOutputTruncated sets the "output_truncated" field.
func (_u *PayloadAuditLogUpdate) SetOutputTruncated(v bool) *PayloadAuditLogUpdate {
	_u.mutation.SetOutputTruncated(v)
	return _u
}

// SetNillableOutputTruncated sets the "output_truncated" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableOutputTruncated(v *bool) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetOutputTruncated(*v)
	}
	return _u
}

// SetOutputOmitted sets the "output_omitted" field.
func (_u *PayloadAuditLogUpdate) SetOutputOmitted(v bool) *PayloadAuditLogUpdate {
	_u.mutation.SetOutputOmitted(v)
	return _u
}

// SetNillableOutputOmitted sets the "output_omitted" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableOutputOmitted(v *bool) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetOutputOmitted(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *PayloadAuditLogUpdate) SetErrorMessage(v string) *PayloadAuditLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *PayloadAuditLogUpdate) SetNillableErrorMessage(v *string) *PayloadAuditLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// Mutation returns the PayloadAuditLogMutation object of the builder.
func (_u *PayloadAuditLogUpdate) Mutation() *PayloadAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PayloadAuditLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PayloadAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PayloadAuditLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payloadauditlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PayloadAuditLogUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := payloadauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := payloadauditlog.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyName(); ok {
		if err := payloadauditlog.APIKeyNameValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.api_key_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := payloadauditlog.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := payloadauditlog.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := payloadauditlog.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := payloadauditlog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := payloadauditlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := payloadauditlog.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputExcerpt(); ok {
		if err := payloadauditlog.InputExcerptValidator(v); err != nil {
			return &ValidationError{Name: "input_excerpt", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.input_excerpt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputExcerpt(); ok {
		if err := payloadauditlog.OutputExcerptValidator(v); err != nil {
			return &ValidationError{Name: "output_excerpt", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.output_excerpt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputFormat(); ok {
		if err := payloadauditlog.InputFormatValidator(v); err != nil {
			return &ValidationError{Name: "input_format", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.input_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputFormat(); ok {
		if err := payloadauditlog.OutputFormatValidator(v); err != nil {
			return &ValidationError{Name: "output_format", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.output_format": %w`, err)}
		}
	}
	return nil
}

func (_u *PayloadAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payloadauditlog.Table, payloadauditlog.Columns, sqlgraph.NewFieldSpec(payloadauditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payloadauditlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(payloadauditlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(payloadauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(payloadauditlog.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(payloadauditlog.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(payloadauditlog.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(payloadauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(payloadauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(payloadauditlog.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyName(); ok {
		_spec.SetField(payloadauditlog.FieldAPIKeyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(payloadauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(payloadauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(payloadauditlog.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(payloadauditlog.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(payloadauditlog.FieldClientIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(payloadauditlog.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(payloadauditlog.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(payloadauditlog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(payloadauditlog.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(payloadauditlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(payloadauditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(payloadauditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(payloadauditlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(payloadauditlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputExcerpt(); ok {
		_spec.SetField(payloadauditlog.FieldInputExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputExcerpt(); ok {
		_spec.SetField(payloadauditlog.FieldOutputExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputBody(); ok {
		_spec.SetField(payloadauditlog.FieldInputBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputBody(); ok {
		_spec.SetField(payloadauditlog.FieldOutputBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputFormat(); ok {
		_spec.SetField(payloadauditlog.FieldInputFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputFormat(); ok {
		_spec.SetField(payloadauditlog.FieldOutputFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputBytes(); ok {
		_spec.SetField(payloadauditlog.FieldInputBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputBytes(); ok {
		_spec.AddField(payloadauditlog.FieldInputBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputBytes(); ok {
		_spec.SetField(payloadauditlog.FieldOutputBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputBytes(); ok {
		_spec.AddField(payloadauditlog.FieldOutputBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputTruncated(); ok {
		_spec.SetField(payloadauditlog.FieldInputTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutputTruncated(); ok {
		_spec.SetField(payloadauditlog.FieldOutputTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutputOmitted(); ok {
		_spec.SetField(payloadauditlog.FieldOutputOmitted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(payloadauditlog.FieldErrorMessage, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payloadauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PayloadAuditLogUpdateOne is the builder for updating a single PayloadAuditLog entity.
type PayloadAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PayloadAuditLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PayloadAuditLogUpdateOne) SetUpdatedAt(v time.Time) *PayloadAuditLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *PayloadAuditLogUpdateOne) SetRequestID(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableRequestID(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PayloadAuditLogUpdateOne) SetUserID(v int64) *PayloadAuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableUserID(v *int64) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *PayloadAuditLogUpdateOne) AddUserID(v int64) *PayloadAuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *PayloadAuditLogUpdateOne) ClearUserID() *PayloadAuditLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *PayloadAuditLogUpdateOne) SetUserEmail(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableUserEmail(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *PayloadAuditLogUpdateOne) SetAPIKeyID(v int64) *PayloadAuditLogUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableAPIKeyID(v *int64) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *PayloadAuditLogUpdateOne) AddAPIKeyID(v int64) *PayloadAuditLogUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *PayloadAuditLogUpdateOne) ClearAPIKeyID() *PayloadAuditLogUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAPIKeyName sets the "api_key_name" field.
func (_u *PayloadAuditLogUpdateOne) SetAPIKeyName(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetAPIKeyName(v)
	return _u
}

// SetNillableAPIKeyName sets the "api_key_name" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableAPIKeyName(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyName(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PayloadAuditLogUpdateOne) SetGroupID(v int64) *PayloadAuditLogUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableGroupID(v *int64) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *PayloadAuditLogUpdateOne) AddGroupID(v int64) *PayloadAuditLogUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *PayloadAuditLogUpdateOne) ClearGroupID() *PayloadAuditLogUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *PayloadAuditLogUpdateOne) SetGroupName(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableGroupName(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *PayloadAuditLogUpdateOne) SetClientIP(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableClientIP(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *PayloadAuditLogUpdateOne) SetEndpoint(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableEndpoint(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PayloadAuditLogUpdateOne) SetProvider(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableProvider(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *PayloadAuditLogUpdateOne) SetModel(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableModel(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *PayloadAuditLogUpdateOne) SetUpstreamModel(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableUpstreamModel(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetStream sets the "stream" field.
func (_u *PayloadAuditLogUpdateOne) SetStream(v bool) *PayloadAuditLogUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableStream(v *bool) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *PayloadAuditLogUpdateOne) SetStatusCode(v int) *PayloadAuditLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableStatusCode(v *int) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *PayloadAuditLogUpdateOne) AddStatusCode(v int) *PayloadAuditLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *PayloadAuditLogUpdateOne) SetDurationMs(v int) *PayloadAuditLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableDurationMs(v *int) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *PayloadAuditLogUpdateOne) AddDurationMs(v int) *PayloadAuditLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetInputExcerpt sets the "input_excerpt" field.
func (_u *PayloadAuditLogUpdateOne) SetInputExcerpt(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetInputExcerpt(v)
	return _u
}

// SetNillableInputExcerpt sets the "input_excerpt" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableInputExcerpt(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetInputExcerpt(*v)
	}
	return _u
}

// SetOutputExcerpt sets the "output_excerpt" field.
func (_u *PayloadAuditLogUpdateOne) SetOutputExcerpt(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetOutputExcerpt(v)
	return _u
}

// SetNillableOutputExcerpt sets the "output_excerpt" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableOutputExcerpt(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetOutputExcerpt(*v)
	}
	return _u
}

// SetInputBody sets the "input_body" field.
func (_u *PayloadAuditLogUpdateOne) SetInputBody(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetInputBody(v)
	return _u
}

// SetNillableInputBody sets the "input_body" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableInputBody(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetInputBody(*v)
	}
	return _u
}

// SetOutputBody sets the "output_body" field.
func (_u *PayloadAuditLogUpdateOne) SetOutputBody(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetOutputBody(v)
	return _u
}

// SetNillableOutputBody sets the "output_body" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableOutputBody(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetOutputBody(*v)
	}
	return _u
}

// SetInputFormat sets the "input_format" field.
func (_u *PayloadAuditLogUpdateOne) SetInputFormat(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetInputFormat(v)
	return _u
}

// SetNillableInputFormat sets the "input_format" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableInputFormat(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetInputFormat(*v)
	}
	return _u
}

// SetOutputFormat sets the "output_format" field.
func (_u *PayloadAuditLogUpdateOne) SetOutputFormat(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetOutputFormat(v)
	return _u
}

// SetNillableOutputFormat sets the "output_format" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableOutputFormat(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetOutputFormat(*v)
	}
	return _u
}

// SetInputBytes sets the "input_bytes" field.
func (_u *PayloadAuditLogUpdateOne) SetInputBytes(v int) *PayloadAuditLogUpdateOne {
	_u.mutation.ResetInputBytes()
	_u.mutation.SetInputBytes(v)
	return _u
}

// SetNillableInputBytes sets the "input_bytes" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableInputBytes(v *int) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetInputBytes(*v)
	}
	return _u
}

// AddInputBytes adds value to the "input_bytes" field.
func (_u *PayloadAuditLogUpdateOne) AddInputBytes(v int) *PayloadAuditLogUpdateOne {
	_u.mutation.AddInputBytes(v)
	return _u
}

// SetOutputBytes sets the "output_bytes" field.
func (_u *PayloadAuditLogUpdateOne) SetOutputBytes(v int) *PayloadAuditLogUpdateOne {
	_u.mutation.ResetOutputBytes()
	_u.mutation.SetOutputBytes(v)
	return _u
}

// SetNillableOutputBytes sets the "output_bytes" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableOutputBytes(v *int) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetOutputBytes(*v)
	}
	return _u
}

// AddOutputBytes adds value to the "output_bytes" field.
func (_u *PayloadAuditLogUpdateOne) AddOutputBytes(v int) *PayloadAuditLogUpdateOne {
	_u.mutation.AddOutputBytes(v)
	return _u
}

// SetInputTruncated sets the "input_truncated" field.
func (_u *PayloadAuditLogUpdateOne) SetInputTruncated(v bool) *PayloadAuditLogUpdateOne {
	_u.mutation.SetInputTruncated(v)
	return _u
}

// SetNillableInputTruncated sets the "input_truncated" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableInputTruncated(v *bool) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetInputTruncated(*v)
	}
	return _u
}

// SetOutputTruncated sets the "output_truncated" field.
func (_u *PayloadAuditLogUpdateOne) SetOutputTruncated(v bool) *PayloadAuditLogUpdateOne {
	_u.mutation.SetOutputTruncated(v)
	return _u
}

// SetNillableOutputTruncated sets the "output_truncated" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableOutputTruncated(v *bool) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetOutputTruncated(*v)
	}
	return _u
}

// SetOutputOmitted sets the "output_omitted" field.
func (_u *PayloadAuditLogUpdateOne) SetOutputOmitted(v bool) *PayloadAuditLogUpdateOne {
	_u.mutation.SetOutputOmitted(v)
	return _u
}

// SetNillableOutputOmitted sets the "output_omitted" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableOutputOmitted(v *bool) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetOutputOmitted(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *PayloadAuditLogUpdateOne) SetErrorMessage(v string) *PayloadAuditLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *PayloadAuditLogUpdateOne) SetNillableErrorMessage(v *string) *PayloadAuditLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// Mutation returns the PayloadAuditLogMutation object of the builder.
func (_u *PayloadAuditLogUpdateOne) Mutation() *PayloadAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the PayloadAuditLogUpdate builder.
func (_u *PayloadAuditLogUpdateOne) Where(ps ...predicate.PayloadAuditLog) *PayloadAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PayloadAuditLogUpdateOne) Select(field string, fields ...string) *PayloadAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PayloadAuditLog entity.
func (_u *PayloadAuditLogUpdateOne) Save(ctx context.Context) (*PayloadAuditLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadAuditLogUpdateOne) SaveX(ctx context.Context) *PayloadAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PayloadAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PayloadAuditLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payloadauditlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PayloadAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := payloadauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := payloadauditlog.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyName(); ok {
		if err := payloadauditlog.APIKeyNameValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.api_key_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := payloadauditlog.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := payloadauditlog.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := payloadauditlog.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := payloadauditlog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := payloadauditlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := payloadauditlog.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputExcerpt(); ok {
		if err := payloadauditlog.InputExcerptValidator(v); err != nil {
			return &ValidationError{Name: "input_excerpt", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.input_excerpt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputExcerpt(); ok {
		if err := payloadauditlog.OutputExcerptValidator(v); err != nil {
			return &ValidationError{Name: "output_excerpt", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.output_excerpt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputFormat(); ok {
		if err := payloadauditlog.InputFormatValidator(v); err != nil {
			return &ValidationError{Name: "input_format", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.input_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputFormat(); ok {
		if err := payloadauditlog.OutputFormatValidator(v); err != nil {
			return &ValidationError{Name: "output_format", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.output_format": %w`, err)}
		}
	}
	return nil
}

func (_u *PayloadAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *PayloadAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payloadauditlog.Table, payloadauditlog.Columns, sqlgraph.NewFieldSpec(payloadauditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PayloadAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payloadauditlog.FieldID)
		for _, f := range fields {
			if !payloadauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payloadauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payloadauditlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(payloadauditlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(payloadauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(payloadauditlog.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(payloadauditlog.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(payloadauditlog.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(payloadauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(payloadauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(payloadauditlog.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyName(); ok {
		_spec.SetField(payloadauditlog.FieldAPIKeyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(payloadauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(payloadauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(payloadauditlog.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(payloadauditlog.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(payloadauditlog.FieldClientIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(payloadauditlog.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(payloadauditlog.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(payloadauditlog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(payloadauditlog.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(payloadauditlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(payloadauditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(payloadauditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(payloadauditlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(payloadauditlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputExcerpt(); ok {
		_spec.SetField(payloadauditlog.FieldInputExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputExcerpt(); ok {
		_spec.SetField(payloadauditlog.FieldOutputExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputBody(); ok {
		_spec.SetField(payloadauditlog.FieldInputBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputBody(); ok {
		_spec.SetField(payloadauditlog.FieldOutputBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputFormat(); ok {
		_spec.SetField(payloadauditlog.FieldInputFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputFormat(); ok {
		_spec.SetField(payloadauditlog.FieldOutputFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputBytes(); ok {
		_spec.SetField(payloadauditlog.FieldInputBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputBytes(); ok {
		_spec.AddField(payloadauditlog.FieldInputBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputBytes(); ok {
		_spec.SetField(payloadauditlog.FieldOutputBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputBytes(); ok {
		_spec.AddField(payloadauditlog.FieldOutputBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputTruncated(); ok {
		_spec.SetField(payloadauditlog.FieldInputTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutputTruncated(); ok {
		_spec.SetField(payloadauditlog.FieldOutputTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutputOmitted(); ok {
		_spec.SetField(payloadauditlog.FieldOutputOmitted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(payloadauditlog.FieldErrorMessage, field.TypeString, value)
	}
	_node = &PayloadAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payloadauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
