// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/payloadauditlog"
)

// PayloadAuditLogCreate is the builder for creating a PayloadAuditLog entity.
type PayloadAuditLogCreate struct {
	config
	mutation *PayloadAuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PayloadAuditLogCreate) SetCreatedAt(v time.Time) *PayloadAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableCreatedAt(v *time.Time) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PayloadAuditLogCreate) SetUpdatedAt(v time.Time) *PayloadAuditLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableUpdatedAt(v *time.Time) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *PayloadAuditLogCreate) SetRequestID(v string) *PayloadAuditLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableRequestID(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PayloadAuditLogCreate) SetUserID(v int64) *PayloadAuditLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableUserID(v *int64) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *PayloadAuditLogCreate) SetUserEmail(v string) *PayloadAuditLogCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableUserEmail(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *PayloadAuditLogCreate) SetAPIKeyID(v int64) *PayloadAuditLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableAPIKeyID(v *int64) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetAPIKeyName sets the "api_key_name" field.
func (_c *PayloadAuditLogCreate) SetAPIKeyName(v string) *PayloadAuditLogCreate {
	_c.mutation.SetAPIKeyName(v)
	return _c
}

// SetNillableAPIKeyName sets the "api_key_name" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableAPIKeyName(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetAPIKeyName(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PayloadAuditLogCreate) SetGroupID(v int64) *PayloadAuditLogCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableGroupID(v *int64) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *PayloadAuditLogCreate) SetGroupName(v string) *PayloadAuditLogCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableGroupName(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetGroupName(*v)
	}
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *PayloadAuditLogCreate) SetClientIP(v string) *PayloadAuditLogCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableClientIP(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *PayloadAuditLogCreate) SetEndpoint(v string) *PayloadAuditLogCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableEndpoint(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *PayloadAuditLogCreate) SetProvider(v string) *PayloadAuditLogCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableProvider(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *PayloadAuditLogCreate) SetModel(v string) *PayloadAuditLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableModel(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *PayloadAuditLogCreate) SetUpstreamModel(v string) *PayloadAuditLogCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableUpstreamModel(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetStream sets the "stream" field.
func (_c *PayloadAuditLogCreate) SetStream(v bool) *PayloadAuditLogCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableStream(v *bool) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *PayloadAuditLogCreate) SetStatusCode(v int) *PayloadAuditLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableStatusCode(v *int) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *PayloadAuditLogCreate) SetDurationMs(v int) *PayloadAuditLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableDurationMs(v *int) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetInputExcerpt sets the "input_excerpt" field.
func (_c *PayloadAuditLogCreate) SetInputExcerpt(v string) *PayloadAuditLogCreate {
	_c.mutation.SetInputExcerpt(v)
	return _c
}

// SetNillableInputExcerpt sets the "input_excerpt" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableInputExcerpt(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetInputExcerpt(*v)
	}
	return _c
}

// SetOutputExcerpt sets the "output_excerpt" field.
func (_c *PayloadAuditLogCreate) SetOutputExcerpt(v string) *PayloadAuditLogCreate {
	_c.mutation.SetOutputExcerpt(v)
	return _c
}

// SetNillableOutputExcerpt sets the "output_excerpt" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableOutputExcerpt(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetOutputExcerpt(*v)
	}
	return _c
}

// SetInputBody sets the "input_body" field.
func (_c *PayloadAuditLogCreate) SetInputBody(v string) *PayloadAuditLogCreate {
	_c.mutation.SetInputBody(v)
	return _c
}

// SetNillableInputBody sets the "input_body" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableInputBody(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetInputBody(*v)
	}
	return _c
}

// SetOutputBody sets the "output_body" field.
func (_c *PayloadAuditLogCreate) SetOutputBody(v string) *PayloadAuditLogCreate {
	_c.mutation.SetOutputBody(v)
	return _c
}

// SetNillableOutputBody sets the "output_body" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableOutputBody(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetOutputBody(*v)
	}
	return _c
}

// SetInputFormat sets the "input_format" field.
func (_c *PayloadAuditLogCreate) SetInputFormat(v string) *PayloadAuditLogCreate {
	_c.mutation.SetInputFormat(v)
	return _c
}

// SetNillableInputFormat sets the "input_format" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableInputFormat(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetInputFormat(*v)
	}
	return _c
}

// SetOutputFormat sets the "output_format" field.
func (_c *PayloadAuditLogCreate) SetOutputFormat(v string) *PayloadAuditLogCreate {
	_c.mutation.SetOutputFormat(v)
	return _c
}

// SetNillableOutputFormat sets the "output_format" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableOutputFormat(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetOutputFormat(*v)
	}
	return _c
}

// SetInputBytes sets the "input_bytes" field.
func (_c *PayloadAuditLogCreate) SetInputBytes(v int) *PayloadAuditLogCreate {
	_c.mutation.SetInputBytes(v)
	return _c
}

// SetNillableInputBytes sets the "input_bytes" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableInputBytes(v *int) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetInputBytes(*v)
	}
	return _c
}

// SetOutputBytes sets the "output_bytes" field.
func (_c *PayloadAuditLogCreate) SetOutputBytes(v int) *PayloadAuditLogCreate {
	_c.mutation.SetOutputBytes(v)
	return _c
}

// SetNillableOutputBytes sets the "output_bytes" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableOutputBytes(v *int) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetOutputBytes(*v)
	}
	return _c
}

// SetInputTruncated sets the "input_truncated" field.
func (_c *PayloadAuditLogCreate) SetInputTruncated(v bool) *PayloadAuditLogCreate {
	_c.mutation.SetInputTruncated(v)
	return _c
}

// SetNillableInputTruncated sets the "input_truncated" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableInputTruncated(v *bool) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetInputTruncated(*v)
	}
	return _c
}

// SetOutputTruncated sets the "output_truncated" field.
func (_c *PayloadAuditLogCreate) SetOutputTruncated(v bool) *PayloadAuditLogCreate {
	_c.mutation.SetOutputTruncated(v)
	return _c
}

// SetNillableOutputTruncated sets the "output_truncated" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableOutputTruncated(v *bool) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetOutputTruncated(*v)
	}
	return _c
}

// SetOutputOmitted sets the "output_omitted" field.
func (_c *PayloadAuditLogCreate) SetOutputOmitted(v bool) *PayloadAuditLogCreate {
	_c.mutation.SetOutputOmitted(v)
	return _c
}

// SetNillableOutputOmitted sets the "output_omitted" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableOutputOmitted(v *bool) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetOutputOmitted(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *PayloadAuditLogCreate) SetErrorMessage(v string) *PayloadAuditLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *PayloadAuditLogCreate) SetNillableErrorMessage(v *string) *PayloadAuditLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// Mutation returns the PayloadAuditLogMutation object of the builder.
func (_c *PayloadAuditLogCreate) Mutation() *PayloadAuditLogMutation {
	return _c.mutation
}

// Save creates the PayloadAuditLog in the database.
func (_c *PayloadAuditLogCreate) Save(ctx context.Context) (*PayloadAuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PayloadAuditLogCreate) SaveX(ctx context.Context) *PayloadAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PayloadAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PayloadAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PayloadAuditLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := payloadauditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := payloadauditlog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := payloadauditlog.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		v := payloadauditlog.DefaultUserEmail
		_c.mutation.SetUserEmail(v)
	}
	if _, ok := _c.mutation.APIKeyName(); !ok {
		v := payloadauditlog.DefaultAPIKeyName
		_c.mutation.SetAPIKeyName(v)
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		v := payloadauditlog.DefaultGroupName
		_c.mutation.SetGroupName(v)
	}
	if _, ok := _c.mutation.ClientIP(); !ok {
		v := payloadauditlog.DefaultClientIP
		_c.mutation.SetClientIP(v)
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		v := payloadauditlog.DefaultEndpoint
		_c.mutation.SetEndpoint(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := payloadauditlog.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := payloadauditlog.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		v := payloadauditlog.DefaultUpstreamModel
		_c.mutation.SetUpstreamModel(v)
	}
	if _, ok := _c.mutation.Stream(); !ok {
		v := payloadauditlog.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := payloadauditlog.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := payloadauditlog.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.InputExcerpt(); !ok {
		v := payloadauditlog.DefaultInputExcerpt
		_c.mutation.SetInputExcerpt(v)
	}
	if _, ok := _c.mutation.OutputExcerpt(); !ok {
		v := payloadauditlog.DefaultOutputExcerpt
		_c.mutation.SetOutputExcerpt(v)
	}
	if _, ok := _c.mutation.InputBody(); !ok {
		v := payloadauditlog.DefaultInputBody
		_c.mutation.SetInputBody(v)
	}
	if _, ok := _c.mutation.OutputBody(); !ok {
		v := payloadauditlog.DefaultOutputBody
		_c.mutation.SetOutputBody(v)
	}
	if _, ok := _c.mutation.InputFormat(); !ok {
		v := payloadauditlog.DefaultInputFormat
		_c.mutation.SetInputFormat(v)
	}
	if _, ok := _c.mutation.OutputFormat(); !ok {
		v := payloadauditlog.DefaultOutputFormat
		_c.mutation.SetOutputFormat(v)
	}
	if _, ok := _c.mutation.InputBytes(); !ok {
		v := payloadauditlog.DefaultInputBytes
		_c.mutation.SetInputBytes(v)
	}
	if _, ok := _c.mutation.OutputBytes(); !ok {
		v := payloadauditlog.DefaultOutputBytes
		_c.mutation.SetOutputBytes(v)
	}
	if _, ok := _c.mutation.InputTruncated(); !ok {
		v := payloadauditlog.DefaultInputTruncated
		_c.mutation.SetInputTruncated(v)
	}
	if _, ok := _c.mutation.OutputTruncated(); !ok {
		v := payloadauditlog.DefaultOutputTruncated
		_c.mutation.SetOutputTruncated(v)
	}
	if _, ok := _c.mutation.OutputOmitted(); !ok {
		v := payloadauditlog.DefaultOutputOmitted
		_c.mutation.SetOutputOmitted(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := payloadauditlog.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PayloadAuditLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PayloadAuditLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PayloadAuditLog.updated_at"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "PayloadAuditLog.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := payloadauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		return &ValidationError{Name: "user_email", err: errors.New(`ent: missing required field "PayloadAuditLog.user_email"`)}
	}
	if v, ok := _c.mutation.UserEmail(); ok {
		if err := payloadauditlog.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.user_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyName(); !ok {
		return &ValidationError{Name: "api_key_name", err: errors.New(`ent: missing required field "PayloadAuditLog.api_key_name"`)}
	}
	if v, ok := _c.mutation.APIKeyName(); ok {
		if err := payloadauditlog.APIKeyNameValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.api_key_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "PayloadAuditLog.group_name"`)}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := payloadauditlog.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.group_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientIP(); !ok {
		return &ValidationError{Name: "client_ip", err: errors.New(`ent: missing required field "PayloadAuditLog.client_ip"`)}
	}
	if v, ok := _c.mutation.ClientIP(); ok {
		if err := payloadauditlog.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.client_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "PayloadAuditLog.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := payloadauditlog.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "PayloadAuditLog.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := payloadauditlog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "PayloadAuditLog.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := payloadauditlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "PayloadAuditLog.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := payloadauditlog.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "PayloadAuditLog.stream"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "PayloadAuditLog.status_code"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "PayloadAuditLog.duration_ms"`)}
	}
	if _, ok := _c.mutation.InputExcerpt(); !ok {
		return &ValidationError{Name: "input_excerpt", err: errors.New(`ent: missing required field "PayloadAuditLog.input_excerpt"`)}
	}
	if v, ok := _c.mutation.InputExcerpt(); ok {
		if err := payloadauditlog.InputExcerptValidator(v); err != nil {
			return &ValidationError{Name: "input_excerpt", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.input_excerpt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OutputExcerpt(); !ok {
		return &ValidationError{Name: "output_excerpt", err: errors.New(`ent: missing required field "PayloadAuditLog.output_excerpt"`)}
	}
	if v, ok := _c.mutation.OutputExcerpt(); ok {
		if err := payloadauditlog.OutputExcerptValidator(v); err != nil {
			return &ValidationError{Name: "output_excerpt", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.output_excerpt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputBody(); !ok {
		return &ValidationError{Name: "input_body", err: errors.New(`ent: missing required field "PayloadAuditLog.input_body"`)}
	}
	if _, ok := _c.mutation.OutputBody(); !ok {
		return &ValidationError{Name: "output_body", err: errors.New(`ent: missing required field "PayloadAuditLog.output_body"`)}
	}
	if _, ok := _c.mutation.InputFormat(); !ok {
		return &ValidationError{Name: "input_format", err: errors.New(`ent: missing required field "PayloadAuditLog.input_format"`)}
	}
	if v, ok := _c.mutation.InputFormat(); ok {
		if err := payloadauditlog.InputFormatValidator(v); err != nil {
			return &ValidationError{Name: "input_format", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.input_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OutputFormat(); !ok {
		return &ValidationError{Name: "output_format", err: errors.New(`ent: missing required field "PayloadAuditLog.output_format"`)}
	}
	if v, ok := _c.mutation.OutputFormat(); ok {
		if err := payloadauditlog.OutputFormatValidator(v); err != nil {
			return &ValidationError{Name: "output_format", err: fmt.Errorf(`ent: validator failed for field "PayloadAuditLog.output_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputBytes(); !ok {
		return &ValidationError{Name: "input_bytes", err: errors.New(`ent: missing required field "PayloadAuditLog.input_bytes"`)}
	}
	if _, ok := _c.mutation.OutputBytes(); !ok {
		return &ValidationError{Name: "output_bytes", err: errors.New(`ent: missing required field "PayloadAuditLog.output_bytes"`)}
	}
	if _, ok := _c.mutation.InputTruncated(); !ok {
		return &ValidationError{Name: "input_truncated", err: errors.New(`ent: missing required field "PayloadAuditLog.input_truncated"`)}
	}
	if _, ok := _c.mutation.OutputTruncated(); !ok {
		return &ValidationError{Name: "output_truncated", err: errors.New(`ent: missing required field "PayloadAuditLog.output_truncated"`)}
	}
	if _, ok := _c.mutation.OutputOmitted(); !ok {
		return &ValidationError{Name: "output_omitted", err: errors.New(`ent: missing required field "PayloadAuditLog.output_omitted"`)}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "PayloadAuditLog.error_message"`)}
	}
	return nil
}

func (_c *PayloadAuditLogCreate) sqlSave(ctx context.Context) (*PayloadAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PayloadAuditLogCreate) createSpec() (*PayloadAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &PayloadAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(payloadauditlog.Table, sqlgraph.NewFieldSpec(payloadauditlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(payloadauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(payloadauditlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(payloadauditlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(payloadauditlog.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(payloadauditlog.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(payloadauditlog.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.APIKeyName(); ok {
		_spec.SetField(payloadauditlog.FieldAPIKeyName, field.TypeString, value)
		_node.APIKeyName = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(payloadauditlog.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(payloadauditlog.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(payloadauditlog.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(payloadauditlog.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(payloadauditlog.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(payloadauditlog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(payloadauditlog.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(payloadauditlog.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(payloadauditlog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(payloadauditlog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.InputExcerpt(); ok {
		_spec.SetField(payloadauditlog.FieldInputExcerpt, field.TypeString, value)
		_node.InputExcerpt = value
	}
	if value, ok := _c.mutation.OutputExcerpt(); ok {
		_spec.SetField(payloadauditlog.FieldOutputExcerpt, field.TypeString, value)
		_node.OutputExcerpt = value
	}
	if value, ok := _c.mutation.InputBody(); ok {
		_spec.SetField(payloadauditlog.FieldInputBody, field.TypeString, value)
		_node.InputBody = value
	}
	if value, ok := _c.mutation.OutputBody(); ok {
		_spec.SetField(payloadauditlog.FieldOutputBody, field.TypeString, value)
		_node.OutputBody = value
	}
	if value, ok := _c.mutation.InputFormat(); ok {
		_spec.SetField(payloadauditlog.FieldInputFormat, field.TypeString, value)
		_node.InputFormat = value
	}
	if value, ok := _c.mutation.OutputFormat(); ok {
		_spec.SetField(payloadauditlog.FieldOutputFormat, field.TypeString, value)
		_node.OutputFormat = value
	}
	if value, ok := _c.mutation.InputBytes(); ok {
		_spec.SetField(payloadauditlog.FieldInputBytes, field.TypeInt, value)
		_node.InputBytes = value
	}
	if value, ok := _c.mutation.OutputBytes(); ok {
		_spec.SetField(payloadauditlog.FieldOutputBytes, field.TypeInt, value)
		_node.OutputBytes = value
	}
	if value, ok := _c.mutation.InputTruncated(); ok {
		_spec.SetField(payloadauditlog.FieldInputTruncated, field.TypeBool, value)
		_node.InputTruncated = value
	}
	if value, ok := _c.mutation.OutputTruncated(); ok {
		_spec.SetField(payloadauditlog.FieldOutputTruncated, field.TypeBool, value)
		_node.OutputTruncated = value
	}
	if value, ok := _c.mutation.OutputOmitted(); ok {
		_spec.SetField(payloadauditlog.FieldOutputOmitted, field.TypeBool, value)
		_node.OutputOmitted = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(payloadauditlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PayloadAuditLog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PayloadAuditLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PayloadAuditLogCreate) OnConflict(opts ...sql.ConflictOption) *PayloadAuditLogUpsertOne {
	_c.conflict = opts
	return &PayloadAuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PayloadAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PayloadAuditLogCreate) OnConflictColumns(columns ...string) *PayloadAuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PayloadAuditLogUpsertOne{
		create: _c,
	}
}

type (
	// PayloadAuditLogUpsertOne is the builder for "upsert"-ing
	//  one PayloadAuditLog node.
	PayloadAuditLogUpsertOne struct {
		create *PayloadAuditLogCreate
	}

	// PayloadAuditLogUpsert is the "OnConflict" setter.
	PayloadAuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PayloadAuditLogUpsert) SetUpdatedAt(v time.Time) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateUpdatedAt() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldUpdatedAt)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *PayloadAuditLogUpsert) SetRequestID(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateRequestID() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldRequestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PayloadAuditLogUpsert) SetUserID(v int64) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateUserID() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *PayloadAuditLogUpsert) AddUserID(v int64) *PayloadAuditLogUpsert {
	u.Add(payloadauditlog.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *PayloadAuditLogUpsert) ClearUserID() *PayloadAuditLogUpsert {
	u.SetNull(payloadauditlog.FieldUserID)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *PayloadAuditLogUpsert) SetUserEmail(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateUserEmail() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldUserEmail)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *PayloadAuditLogUpsert) SetAPIKeyID(v int64) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateAPIKeyID() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *PayloadAuditLogUpsert) AddAPIKeyID(v int64) *PayloadAuditLogUpsert {
	u.Add(payloadauditlog.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *PayloadAuditLogUpsert) ClearAPIKeyID() *PayloadAuditLogUpsert {
	u.SetNull(payloadauditlog.FieldAPIKeyID)
	return u
}

// SetAPIKeyName sets the "api_key_name" field.
func (u *PayloadAuditLogUpsert) SetAPIKeyName(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldAPIKeyName, v)
	return u
}

// UpdateAPIKeyName sets the "api_key_name" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateAPIKeyName() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldAPIKeyName)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *PayloadAuditLogUpsert) SetGroupID(v int64) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateGroupID() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *PayloadAuditLogUpsert) AddGroupID(v int64) *PayloadAuditLogUpsert {
	u.Add(payloadauditlog.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PayloadAuditLogUpsert) ClearGroupID() *PayloadAuditLogUpsert {
	u.SetNull(payloadauditlog.FieldGroupID)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *PayloadAuditLogUpsert) SetGroupName(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateGroupName() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldGroupName)
	return u
}

// SetClientIP sets the "client_ip" field.
func (u *PayloadAuditLogUpsert) SetClientIP(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldClientIP, v)
	return u
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateClientIP() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldClientIP)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *PayloadAuditLogUpsert) SetEndpoint(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateEndpoint() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldEndpoint)
	return u
}

// SetProvider sets the "provider" field.
func (u *PayloadAuditLogUpsert) SetProvider(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateProvider() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *PayloadAuditLogUpsert) SetModel(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateModel() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PayloadAuditLogUpsert) SetUpstreamModel(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateUpstreamModel() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldUpstreamModel)
	return u
}

// SetStream sets the "stream" field.
func (u *PayloadAuditLogUpsert) SetStream(v bool) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateStream() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldStream)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *PayloadAuditLogUpsert) SetStatusCode(v int) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateStatusCode() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *PayloadAuditLogUpsert) AddStatusCode(v int) *PayloadAuditLogUpsert {
	u.Add(payloadauditlog.FieldStatusCode, v)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *PayloadAuditLogUpsert) SetDurationMs(v int) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateDurationMs() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *PayloadAuditLogUpsert) AddDurationMs(v int) *PayloadAuditLogUpsert {
	u.Add(payloadauditlog.FieldDurationMs, v)
	return u
}

// SetInputExcerpt sets the "input_excerpt" field.
func (u *PayloadAuditLogUpsert) SetInputExcerpt(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldInputExcerpt, v)
	return u
}

// UpdateInputExcerpt sets the "input_excerpt" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateInputExcerpt() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldInputExcerpt)
	return u
}

// SetOutputExcerpt sets the "output_excerpt" field.
func (u *PayloadAuditLogUpsert) SetOutputExcerpt(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldOutputExcerpt, v)
	return u
}

// UpdateOutputExcerpt sets the "output_excerpt" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateOutputExcerpt() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldOutputExcerpt)
	return u
}

// SetInputBody sets the "input_body" field.
func (u *PayloadAuditLogUpsert) SetInputBody(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldInputBody, v)
	return u
}

// UpdateInputBody sets the "input_body" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateInputBody() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldInputBody)
	return u
}

// SetOutputBody sets the "output_body" field.
func (u *PayloadAuditLogUpsert) SetOutputBody(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldOutputBody, v)
	return u
}

// UpdateOutputBody sets the "output_body" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateOutputBody() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldOutputBody)
	return u
}

// SetInputFormat sets the "input_format" field.
func (u *PayloadAuditLogUpsert) SetInputFormat(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldInputFormat, v)
	return u
}

// UpdateInputFormat sets the "input_format" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateInputFormat() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldInputFormat)
	return u
}

// SetOutputFormat sets the "output_format" field.
func (u *PayloadAuditLogUpsert) SetOutputFormat(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldOutputFormat, v)
	return u
}

// UpdateOutputFormat sets the "output_format" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateOutputFormat() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldOutputFormat)
	return u
}

// SetInputBytes sets the "input_bytes" field.
func (u *PayloadAuditLogUpsert) SetInputBytes(v int) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldInputBytes, v)
	return u
}

// UpdateInputBytes sets the "input_bytes" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateInputBytes() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldInputBytes)
	return u
}

// AddInputBytes adds v to the "input_bytes" field.
func (u *PayloadAuditLogUpsert) AddInputBytes(v int) *PayloadAuditLogUpsert {
	u.Add(payloadauditlog.FieldInputBytes, v)
	return u
}

// SetOutputBytes sets the "output_bytes" field.
func (u *PayloadAuditLogUpsert) SetOutputBytes(v int) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldOutputBytes, v)
	return u
}

// UpdateOutputBytes sets the "output_bytes" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateOutputBytes() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldOutputBytes)
	return u
}

// AddOutputBytes adds v to the "output_bytes" field.
func (u *PayloadAuditLogUpsert) AddOutputBytes(v int) *PayloadAuditLogUpsert {
	u.Add(payloadauditlog.FieldOutputBytes, v)
	return u
}

// SetInputTruncated sets the "input_truncated" field.
func (u *PayloadAuditLogUpsert) SetInputTruncated(v bool) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldInputTruncated, v)
	return u
}

// UpdateInputTruncated sets the "input_truncated" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateInputTruncated() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldInputTruncated)
	return u
}

// SetOutputTruncated sets the "output_truncated" field.
func (u *PayloadAuditLogUpsert) SetOutputTruncated(v bool) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldOutputTruncated, v)
	return u
}

// UpdateOutputTruncated sets the "output_truncated" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateOutputTruncated() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldOutputTruncated)
	return u
}

// SetOutputOmitted sets the "output_omitted" field.
func (u *PayloadAuditLogUpsert) SetOutputOmitted(v bool) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldOutputOmitted, v)
	return u
}

// UpdateOutputOmitted sets the "output_omitted" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateOutputOmitted() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldOutputOmitted)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *PayloadAuditLogUpsert) SetErrorMessage(v string) *PayloadAuditLogUpsert {
	u.Set(payloadauditlog.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *PayloadAuditLogUpsert) UpdateErrorMessage() *PayloadAuditLogUpsert {
	u.SetExcluded(payloadauditlog.FieldErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PayloadAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PayloadAuditLogUpsertOne) UpdateNewValues() *PayloadAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(payloadauditlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PayloadAuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PayloadAuditLogUpsertOne) Ignore() *PayloadAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PayloadAuditLogUpsertOne) DoNothing() *PayloadAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PayloadAuditLogCreate.OnConflict
// documentation for more info.
func (u *PayloadAuditLogUpsertOne) Update(set func(*PayloadAuditLogUpsert)) *PayloadAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PayloadAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PayloadAuditLogUpsertOne) SetUpdatedAt(v time.Time) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateUpdatedAt() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestID sets the "request_id" field.
func (u *PayloadAuditLogUpsertOne) SetRequestID(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateRequestID() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *PayloadAuditLogUpsertOne) SetUserID(v int64) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *PayloadAuditLogUpsertOne) AddUserID(v int64) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateUserID() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *PayloadAuditLogUpsertOne) ClearUserID() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *PayloadAuditLogUpsertOne) SetUserEmail(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateUserEmail() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateUserEmail()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *PayloadAuditLogUpsertOne) SetAPIKeyID(v int64) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *PayloadAuditLogUpsertOne) AddAPIKeyID(v int64) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateAPIKeyID() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *PayloadAuditLogUpsertOne) ClearAPIKeyID() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAPIKeyName sets the "api_key_name" field.
func (u *PayloadAuditLogUpsertOne) SetAPIKeyName(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetAPIKeyName(v)
	})
}

// UpdateAPIKeyName sets the "api_key_name" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateAPIKeyName() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateAPIKeyName()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PayloadAuditLogUpsertOne) SetGroupID(v int64) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *PayloadAuditLogUpsertOne) AddGroupID(v int64) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateGroupID() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PayloadAuditLogUpsertOne) ClearGroupID() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.ClearGroupID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *PayloadAuditLogUpsertOne) SetGroupName(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateGroupName() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateGroupName()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *PayloadAuditLogUpsertOne) SetClientIP(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateClientIP() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateClientIP()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *PayloadAuditLogUpsertOne) SetEndpoint(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateEndpoint() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateEndpoint()
	})
}

// SetProvider sets the "provider" field.
func (u *PayloadAuditLogUpsertOne) SetProvider(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateProvider() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *PayloadAuditLogUpsertOne) SetModel(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateModel() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PayloadAuditLogUpsertOne) SetUpstreamModel(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateUpstreamModel() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetStream sets the "stream" field.
func (u *PayloadAuditLogUpsertOne) SetStream(v bool) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateStream() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateStream()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *PayloadAuditLogUpsertOne) SetStatusCode(v int) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *PayloadAuditLogUpsertOne) AddStatusCode(v int) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateStatusCode() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *PayloadAuditLogUpsertOne) SetDurationMs(v int) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *PayloadAuditLogUpsertOne) AddDurationMs(v int) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateDurationMs() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateDurationMs()
	})
}

// SetInputExcerpt sets the "input_excerpt" field.
func (u *PayloadAuditLogUpsertOne) SetInputExcerpt(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputExcerpt(v)
	})
}

// UpdateInputExcerpt sets the "input_excerpt" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateInputExcerpt() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputExcerpt()
	})
}

// SetOutputExcerpt sets the "output_excerpt" field.
func (u *PayloadAuditLogUpsertOne) SetOutputExcerpt(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputExcerpt(v)
	})
}

// UpdateOutputExcerpt sets the "output_excerpt" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateOutputExcerpt() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputExcerpt()
	})
}

// SetInputBody sets the "input_body" field.
func (u *PayloadAuditLogUpsertOne) SetInputBody(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputBody(v)
	})
}

// UpdateInputBody sets the "input_body" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateInputBody() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputBody()
	})
}

// SetOutputBody sets the "output_body" field.
func (u *PayloadAuditLogUpsertOne) SetOutputBody(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputBody(v)
	})
}

// UpdateOutputBody sets the "output_body" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateOutputBody() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputBody()
	})
}

// SetInputFormat sets the "input_format" field.
func (u *PayloadAuditLogUpsertOne) SetInputFormat(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputFormat(v)
	})
}

// UpdateInputFormat sets the "input_format" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateInputFormat() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputFormat()
	})
}

// SetOutputFormat sets the "output_format" field.
func (u *PayloadAuditLogUpsertOne) SetOutputFormat(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputFormat(v)
	})
}

// UpdateOutputFormat sets the "output_format" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateOutputFormat() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputFormat()
	})
}

// SetInputBytes sets the "input_bytes" field.
func (u *PayloadAuditLogUpsertOne) SetInputBytes(v int) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputBytes(v)
	})
}

// AddInputBytes adds v to the "input_bytes" field.
func (u *PayloadAuditLogUpsertOne) AddInputBytes(v int) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddInputBytes(v)
	})
}

// UpdateInputBytes sets the "input_bytes" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateInputBytes() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputBytes()
	})
}

// SetOutputBytes sets the "output_bytes" field.
func (u *PayloadAuditLogUpsertOne) SetOutputBytes(v int) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputBytes(v)
	})
}

// AddOutputBytes adds v to the "output_bytes" field.
func (u *PayloadAuditLogUpsertOne) AddOutputBytes(v int) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddOutputBytes(v)
	})
}

// UpdateOutputBytes sets the "output_bytes" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateOutputBytes() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputBytes()
	})
}

// SetInputTruncated sets the "input_truncated" field.
func (u *PayloadAuditLogUpsertOne) SetInputTruncated(v bool) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputTruncated(v)
	})
}

// UpdateInputTruncated sets the "input_truncated" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateInputTruncated() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputTruncated()
	})
}

// SetOutputTruncated sets the "output_truncated" field.
func (u *PayloadAuditLogUpsertOne) SetOutputTruncated(v bool) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputTruncated(v)
	})
}

// UpdateOutputTruncated sets the "output_truncated" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateOutputTruncated() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputTruncated()
	})
}

// SetOutputOmitted sets the "output_omitted" field.
func (u *PayloadAuditLogUpsertOne) SetOutputOmitted(v bool) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputOmitted(v)
	})
}

// UpdateOutputOmitted sets the "output_omitted" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateOutputOmitted() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputOmitted()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *PayloadAuditLogUpsertOne) SetErrorMessage(v string) *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertOne) UpdateErrorMessage() *PayloadAuditLogUpsertOne {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// Exec executes the query.
func (u *PayloadAuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PayloadAuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PayloadAuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PayloadAuditLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PayloadAuditLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PayloadAuditLogCreateBulk is the builder for creating many PayloadAuditLog entities in bulk.
type PayloadAuditLogCreateBulk struct {
	config
	err      error
	builders []*PayloadAuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the PayloadAuditLog entities in the database.
func (_c *PayloadAuditLogCreateBulk) Save(ctx context.Context) ([]*PayloadAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PayloadAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PayloadAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PayloadAuditLogCreateBulk) SaveX(ctx context.Context) []*PayloadAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PayloadAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PayloadAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PayloadAuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PayloadAuditLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PayloadAuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *PayloadAuditLogUpsertBulk {
	_c.conflict = opts
	return &PayloadAuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PayloadAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PayloadAuditLogCreateBulk) OnConflictColumns(columns ...string) *PayloadAuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PayloadAuditLogUpsertBulk{
		create: _c,
	}
}

// PayloadAuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of PayloadAuditLog nodes.
type PayloadAuditLogUpsertBulk struct {
	create *PayloadAuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PayloadAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PayloadAuditLogUpsertBulk) UpdateNewValues() *PayloadAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(payloadauditlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PayloadAuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PayloadAuditLogUpsertBulk) Ignore() *PayloadAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PayloadAuditLogUpsertBulk) DoNothing() *PayloadAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PayloadAuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *PayloadAuditLogUpsertBulk) Update(set func(*PayloadAuditLogUpsert)) *PayloadAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PayloadAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PayloadAuditLogUpsertBulk) SetUpdatedAt(v time.Time) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateUpdatedAt() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestID sets the "request_id" field.
func (u *PayloadAuditLogUpsertBulk) SetRequestID(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateRequestID() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *PayloadAuditLogUpsertBulk) SetUserID(v int64) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *PayloadAuditLogUpsertBulk) AddUserID(v int64) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateUserID() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *PayloadAuditLogUpsertBulk) ClearUserID() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *PayloadAuditLogUpsertBulk) SetUserEmail(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateUserEmail() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateUserEmail()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *PayloadAuditLogUpsertBulk) SetAPIKeyID(v int64) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *PayloadAuditLogUpsertBulk) AddAPIKeyID(v int64) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateAPIKeyID() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *PayloadAuditLogUpsertBulk) ClearAPIKeyID() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAPIKeyName sets the "api_key_name" field.
func (u *PayloadAuditLogUpsertBulk) SetAPIKeyName(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetAPIKeyName(v)
	})
}

// UpdateAPIKeyName sets the "api_key_name" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateAPIKeyName() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateAPIKeyName()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PayloadAuditLogUpsertBulk) SetGroupID(v int64) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *PayloadAuditLogUpsertBulk) AddGroupID(v int64) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateGroupID() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PayloadAuditLogUpsertBulk) ClearGroupID() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.ClearGroupID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *PayloadAuditLogUpsertBulk) SetGroupName(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateGroupName() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateGroupName()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *PayloadAuditLogUpsertBulk) SetClientIP(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateClientIP() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateClientIP()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *PayloadAuditLogUpsertBulk) SetEndpoint(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateEndpoint() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateEndpoint()
	})
}

// SetProvider sets the "provider" field.
func (u *PayloadAuditLogUpsertBulk) SetProvider(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateProvider() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *PayloadAuditLogUpsertBulk) SetModel(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateModel() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PayloadAuditLogUpsertBulk) SetUpstreamModel(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateUpstreamModel() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetStream sets the "stream" field.
func (u *PayloadAuditLogUpsertBulk) SetStream(v bool) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateStream() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateStream()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *PayloadAuditLogUpsertBulk) SetStatusCode(v int) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *PayloadAuditLogUpsertBulk) AddStatusCode(v int) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateStatusCode() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *PayloadAuditLogUpsertBulk) SetDurationMs(v int) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *PayloadAuditLogUpsertBulk) AddDurationMs(v int) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateDurationMs() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateDurationMs()
	})
}

// SetInputExcerpt sets the "input_excerpt" field.
func (u *PayloadAuditLogUpsertBulk) SetInputExcerpt(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputExcerpt(v)
	})
}

// UpdateInputExcerpt sets the "input_excerpt" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateInputExcerpt() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputExcerpt()
	})
}

// SetOutputExcerpt sets the "output_excerpt" field.
func (u *PayloadAuditLogUpsertBulk) SetOutputExcerpt(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputExcerpt(v)
	})
}

// UpdateOutputExcerpt sets the "output_excerpt" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateOutputExcerpt() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputExcerpt()
	})
}

// SetInputBody sets the "input_body" field.
func (u *PayloadAuditLogUpsertBulk) SetInputBody(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputBody(v)
	})
}

// UpdateInputBody sets the "input_body" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateInputBody() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputBody()
	})
}

// SetOutputBody sets the "output_body" field.
func (u *PayloadAuditLogUpsertBulk) SetOutputBody(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputBody(v)
	})
}

// UpdateOutputBody sets the "output_body" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateOutputBody() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputBody()
	})
}

// SetInputFormat sets the "input_format" field.
func (u *PayloadAuditLogUpsertBulk) SetInputFormat(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputFormat(v)
	})
}

// UpdateInputFormat sets the "input_format" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateInputFormat() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputFormat()
	})
}

// SetOutputFormat sets the "output_format" field.
func (u *PayloadAuditLogUpsertBulk) SetOutputFormat(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputFormat(v)
	})
}

// UpdateOutputFormat sets the "output_format" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateOutputFormat() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputFormat()
	})
}

// SetInputBytes sets the "input_bytes" field.
func (u *PayloadAuditLogUpsertBulk) SetInputBytes(v int) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputBytes(v)
	})
}

// AddInputBytes adds v to the "input_bytes" field.
func (u *PayloadAuditLogUpsertBulk) AddInputBytes(v int) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddInputBytes(v)
	})
}

// UpdateInputBytes sets the "input_bytes" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateInputBytes() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputBytes()
	})
}

// SetOutputBytes sets the "output_bytes" field.
func (u *PayloadAuditLogUpsertBulk) SetOutputBytes(v int) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputBytes(v)
	})
}

// AddOutputBytes adds v to the "output_bytes" field.
func (u *PayloadAuditLogUpsertBulk) AddOutputBytes(v int) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.AddOutputBytes(v)
	})
}

// UpdateOutputBytes sets the "output_bytes" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateOutputBytes() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputBytes()
	})
}

// SetInputTruncated sets the "input_truncated" field.
func (u *PayloadAuditLogUpsertBulk) SetInputTruncated(v bool) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetInputTruncated(v)
	})
}

// UpdateInputTruncated sets the "input_truncated" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateInputTruncated() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateInputTruncated()
	})
}

// SetOutputTruncated sets the "output_truncated" field.
func (u *PayloadAuditLogUpsertBulk) SetOutputTruncated(v bool) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputTruncated(v)
	})
}

// UpdateOutputTruncated sets the "output_truncated" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateOutputTruncated() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputTruncated()
	})
}

// SetOutputOmitted sets the "output_omitted" field.
func (u *PayloadAuditLogUpsertBulk) SetOutputOmitted(v bool) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetOutputOmitted(v)
	})
}

// UpdateOutputOmitted sets the "output_omitted" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateOutputOmitted() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateOutputOmitted()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *PayloadAuditLogUpsertBulk) SetErrorMessage(v string) *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *PayloadAuditLogUpsertBulk) UpdateErrorMessage() *PayloadAuditLogUpsertBulk {
	return u.Update(func(s *PayloadAuditLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// Exec executes the query.
func (u *PayloadAuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PayloadAuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PayloadAuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PayloadAuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
