// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Woo0ood/s2a_for_pcc/ent/payloadauditlog"
)

// PayloadAuditLog is the model entity for the PayloadAuditLog schema.
type PayloadAuditLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// UserEmail holds the value of the "user_email" field.
	UserEmail string `json:"user_email,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// APIKeyName holds the value of the "api_key_name" field.
	APIKeyName string `json:"api_key_name,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// GroupName holds the value of the "group_name" field.
	GroupName string `json:"group_name,omitempty"`
	// ClientIP holds the value of the "client_ip" field.
	ClientIP string `json:"client_ip,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode int `json:"status_code,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int `json:"duration_ms,omitempty"`
	// InputExcerpt holds the value of the "input_excerpt" field.
	InputExcerpt string `json:"input_excerpt,omitempty"`
	// OutputExcerpt holds the value of the "output_excerpt" field.
	OutputExcerpt string `json:"output_excerpt,omitempty"`
	// InputBody holds the value of the "input_body" field.
	InputBody string `json:"input_body,omitempty"`
	// OutputBody holds the value of the "output_body" field.
	OutputBody string `json:"output_body,omitempty"`
	// InputFormat holds the value of the "input_format" field.
	InputFormat string `json:"input_format,omitempty"`
	// OutputFormat holds the value of the "output_format" field.
	OutputFormat string `json:"output_format,omitempty"`
	// InputBytes holds the value of the "input_bytes" field.
	InputBytes int `json:"input_bytes,omitempty"`
	// OutputBytes holds the value of the "output_bytes" field.
	OutputBytes int `json:"output_bytes,omitempty"`
	// InputTruncated holds the value of the "input_truncated" field.
	InputTruncated bool `json:"input_truncated,omitempty"`
	// OutputTruncated holds the value of the "output_truncated" field.
	OutputTruncated bool `json:"output_truncated,omitempty"`
	// OutputOmitted holds the value of the "output_omitted" field.
	OutputOmitted bool `json:"output_omitted,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PayloadAuditLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case payloadauditlog.FieldStream, payloadauditlog.FieldInputTruncated, payloadauditlog.FieldOutputTruncated, payloadauditlog.FieldOutputOmitted:
			values[i] = new(sql.NullBool)
		case payloadauditlog.FieldID, payloadauditlog.FieldUserID, payloadauditlog.FieldAPIKeyID, payloadauditlog.FieldGroupID, payloadauditlog.FieldStatusCode, payloadauditlog.FieldDurationMs, payloadauditlog.FieldInputBytes, payloadauditlog.FieldOutputBytes:
			values[i] = new(sql.NullInt64)
		case payloadauditlog.FieldRequestID, payloadauditlog.FieldUserEmail, payloadauditlog.FieldAPIKeyName, payloadauditlog.FieldGroupName, payloadauditlog.FieldClientIP, payloadauditlog.FieldEndpoint, payloadauditlog.FieldProvider, payloadauditlog.FieldModel, payloadauditlog.FieldUpstreamModel, payloadauditlog.FieldInputExcerpt, payloadauditlog.FieldOutputExcerpt, payloadauditlog.FieldInputBody, payloadauditlog.FieldOutputBody, payloadauditlog.FieldInputFormat, payloadauditlog.FieldOutputFormat, payloadauditlog.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case payloadauditlog.FieldCreatedAt, payloadauditlog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PayloadAuditLog fields.
func (_m *PayloadAuditLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case payloadauditlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case payloadauditlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case payloadauditlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case payloadauditlog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case payloadauditlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case payloadauditlog.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = value.String
			}
		case payloadauditlog.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case payloadauditlog.FieldAPIKeyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_name", values[i])
			} else if value.Valid {
				_m.APIKeyName = value.String
			}
		case payloadauditlog.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case payloadauditlog.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = value.String
			}
		case payloadauditlog.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case payloadauditlog.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case payloadauditlog.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case payloadauditlog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case payloadauditlog.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case payloadauditlog.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case payloadauditlog.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = int(value.Int64)
			}
		case payloadauditlog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = int(value.Int64)
			}
		case payloadauditlog.FieldInputExcerpt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_excerpt", values[i])
			} else if value.Valid {
				_m.InputExcerpt = value.String
			}
		case payloadauditlog.FieldOutputExcerpt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output_excerpt", values[i])
			} else if value.Valid {
				_m.OutputExcerpt = value.String
			}
		case payloadauditlog.FieldInputBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_body", values[i])
			} else if value.Valid {
				_m.InputBody = value.String
			}
		case payloadauditlog.FieldOutputBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output_body", values[i])
			} else if value.Valid {
				_m.OutputBody = value.String
			}
		case payloadauditlog.FieldInputFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_format", values[i])
			} else if value.Valid {
				_m.InputFormat = value.String
			}
		case payloadauditlog.FieldOutputFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output_format", values[i])
			} else if value.Valid {
				_m.OutputFormat = value.String
			}
		case payloadauditlog.FieldInputBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_bytes", values[i])
			} else if value.Valid {
				_m.InputBytes = int(value.Int64)
			}
		case payloadauditlog.FieldOutputBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_bytes", values[i])
			} else if value.Valid {
				_m.OutputBytes = int(value.Int64)
			}
		case payloadauditlog.FieldInputTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field input_truncated", values[i])
			} else if value.Valid {
				_m.InputTruncated = value.Bool
			}
		case payloadauditlog.FieldOutputTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field output_truncated", values[i])
			} else if value.Valid {
				_m.OutputTruncated = value.Bool
			}
		case payloadauditlog.FieldOutputOmitted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field output_omitted", values[i])
			} else if value.Valid {
				_m.OutputOmitted = value.Bool
			}
		case payloadauditlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PayloadAuditLog.
// This includes values selected through modifiers, order, etc.
func (_m *PayloadAuditLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PayloadAuditLog.
// Note that you need to call PayloadAuditLog.Unwrap() before calling this method if this PayloadAuditLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PayloadAuditLog) Update() *PayloadAuditLogUpdateOne {
	return NewPayloadAuditLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PayloadAuditLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PayloadAuditLog) Unwrap() *PayloadAuditLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PayloadAuditLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PayloadAuditLog) String() string {
	var builder strings.Builder
	builder.WriteString("PayloadAuditLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_email=")
	builder.WriteString(_m.UserEmail)
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("api_key_name=")
	builder.WriteString(_m.APIKeyName)
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("group_name=")
	builder.WriteString(_m.GroupName)
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("input_excerpt=")
	builder.WriteString(_m.InputExcerpt)
	builder.WriteString(", ")
	builder.WriteString("output_excerpt=")
	builder.WriteString(_m.OutputExcerpt)
	builder.WriteString(", ")
	builder.WriteString("input_body=")
	builder.WriteString(_m.InputBody)
	builder.WriteString(", ")
	builder.WriteString("output_body=")
	builder.WriteString(_m.OutputBody)
	builder.WriteString(", ")
	builder.WriteString("input_format=")
	builder.WriteString(_m.InputFormat)
	builder.WriteString(", ")
	builder.WriteString("output_format=")
	builder.WriteString(_m.OutputFormat)
	builder.WriteString(", ")
	builder.WriteString("input_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputBytes))
	builder.WriteString(", ")
	builder.WriteString("output_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputBytes))
	builder.WriteString(", ")
	builder.WriteString("input_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTruncated))
	builder.WriteString(", ")
	builder.WriteString("output_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTruncated))
	builder.WriteString(", ")
	builder.WriteString("output_omitted=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputOmitted))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteByte(')')
	return builder.String()
}

// PayloadAuditLogs is a parsable slice of PayloadAuditLog.
type PayloadAuditLogs []*PayloadAuditLog
