// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Woo0ood/s2a_for_pcc/ent/payloadauditlog"
	"github.com/Woo0ood/s2a_for_pcc/ent/predicate"
)

// PayloadAuditLogDelete is the builder for deleting a PayloadAuditLog entity.
type PayloadAuditLogDelete struct {
	config
	hooks    []Hook
	mutation *PayloadAuditLogMutation
}

// Where appends a list predicates to the PayloadAuditLogDelete builder.
func (_d *PayloadAuditLogDelete) Where(ps ...predicate.PayloadAuditLog) *PayloadAuditLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PayloadAuditLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PayloadAuditLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PayloadAuditLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(payloadauditlog.Table, sqlgraph.NewFieldSpec(payloadauditlog.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PayloadAuditLogDeleteOne is the builder for deleting a single PayloadAuditLog entity.
type PayloadAuditLogDeleteOne struct {
	_d *PayloadAuditLogDelete
}

// Where appends a list predicates to the PayloadAuditLogDelete builder.
func (_d *PayloadAuditLogDeleteOne) Where(ps ...predicate.PayloadAuditLog) *PayloadAuditLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PayloadAuditLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{payloadauditlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PayloadAuditLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
